# Generated by Django 4.1.5 on 2023-02-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_date_added"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="product",
            new_name="Product",
        ),
    ]
